[versions]
agp = "9.0.1"
espressoCore = "3.7.0"
junitVersion = "1.3.0"
kotlin = "2.3.10"
activityCompose = "1.12.4"

composeBom = "2026.02.00" # dangerous, breaks things all the time

# Do NOT upgrade to 3.0.0 until this is fixed: https://github.com/Calvin-LL/Reorderable/issues/111
reorderable = "2.3.3"

libphonenumber = "9.0.24"
geocoder = "3.24" # https://repo1.maven.org/maven2/com/googlecode/libphonenumber/geocoder/maven-metadata.xml
#carrier  = "2.21" # https://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/maven-metadata.xml

serialization = "1.10.0"
mockk = "1.14.9"
lazycolumnscrollbar = "2.2.0"
workRuntimeKtx = "2.11.1"
junitJupiter = "6.0.2"

[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
geocoder = { module = "com.googlecode.libphonenumber:geocoder", version.ref = "geocoder" }
#carrier = { module = "com.googlecode.libphonenumber:carrier", version.ref = "carrier" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
mockk = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

