[versions]
agp = "8.7.3"
espressoCore = "3.6.1"
junitVersion = "1.2.1"
kotlin = "2.0.0"
activityCompose = "1.9.3"
composeBom = "2024.12.01"
libphonenumber = "8.13.52"
reorderable = "2.3.3"
serialization = "1.7.1"
mockk = "1.13.10"
lazycolumnscrollbar = "2.2.0"
workRuntimeKtx = "2.10.0"
junitJupiter = "5.8.2"

[libraries]
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
mockk = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
lazycolumnscrollbar = { module = "com.github.nanihadesuka:LazyColumnScrollbar", version.ref = "lazycolumnscrollbar" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

